/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petshop.management.system;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.Barcode128;
import com.itextpdf.text.pdf.BarcodeEAN;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfWriter;
import dao.PetCategoryDao;
import dao.PetDao;
import dao.ProductCategoryDao;
import dao.ProductDao;
import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import model.Pet;
import model.Petcategory;
import model.Product;
import model.Productcategory;
import model.User;

/**
 *
 * @author Admin
 */
public class AddNewProduct extends javax.swing.JFrame {
    public User user;
    class CategoryItem
    {
        private int id = 0;
        private String name = "";
        public CategoryItem(int id, String name) {
            this.id = id;
            this.name = name;
        } 
        public int getId(){
            return id;
        }
        public String getName(){
            return name;
        }
        
        @Override
        public String toString() {
            return name;
        }
    }

    /**
     * Creates new form AddNewProduct
     */
    public AddNewProduct() {
        initComponents();
        btnSave.setEnabled(false);
    }
    
    public AddNewProduct(User user) {
        this.user = user;
        initComponents();
        btnSave.setEnabled(false);
    }
    
    public static void createPDF(String pdfFilename,String myString) {
	    Document doc = new Document();
	    PdfWriter docWriter = null;
	    try {
	        docWriter = PdfWriter.getInstance(doc, new FileOutputStream(System.getProperty("user.dir") + "\\src\\file\\productBarcode\\" + pdfFilename));
	        doc.addAuthor("Pet88 Shop");
	        doc.addCreationDate();
	        doc.addProducer();
	        doc.addCreator("chillyfacts.com");
	        doc.addTitle("chillyfacts Barcode test");
	        doc.setPageSize(PageSize.LETTER);
	        doc.open();
	        PdfContentByte cb = docWriter.getDirectContent();

	        Barcode128 code128 = new Barcode128();
	        code128.setCode(myString.trim());
	        code128.setCodeType(Barcode128.CODE128);
	        com.itextpdf.text.Image code128Image = code128.createImageWithBarcode(cb, null, null);
	        code128Image.setAbsolutePosition(10, 700);
	        code128Image.scalePercent(125);
	        doc.add(code128Image);

	        BarcodeEAN codeEAN = new BarcodeEAN();
	        codeEAN.setCode(myString.trim());
	        codeEAN.setCodeType(BarcodeEAN.EAN13);      
	        com.itextpdf.text.Image codeEANImage = code128.createImageWithBarcode(cb, null, null);
	        codeEANImage.setAbsolutePosition(10, 600);
	        codeEANImage.scalePercent(125);
	        doc.add(codeEANImage);
	    } catch (DocumentException dex) {
	        dex.printStackTrace();
	    } catch (Exception ex) {
	        ex.printStackTrace();
	    } finally {
	        if (doc != null) {
	            doc.close();
	        }
	        if (docWriter != null) {
	            docWriter.close();
	        }
	    }
	}
    
    
    public void validateFields(){
        String name = txtName.getText();
        String description = txtDescription.getText();
        if(!name.equals("") && !description.equals("")){
            btnSave.setEnabled(true);
        } else {
            btnSave.setEnabled(false);
        }
    }
    
    public ImageIcon ResizeImage(String ImagePath){
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cbPetCategory = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        txtVendorPrice = new javax.swing.JTextField();
        txtRetailPrice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        lblImgPath = new javax.swing.JLabel();
        cbProductCategory = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblBarcode = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 134));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 47, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Loài:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        txtName.setText("Ạinline");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 190, -1));

        cbPetCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPetCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cbPetCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 190, -1));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Hủy");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Loại:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Số lượng:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        txtQuantity.setText("20");
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 190, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Giá nhập:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Giá bán:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Mô tả:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jScrollPane1.setHorizontalScrollBar(null);

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 230, 60));

        txtVendorPrice.setText("100000");
        getContentPane().add(txtVendorPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 230, -1));

        txtRetailPrice.setText("150000");
        getContentPane().add(txtRetailPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 230, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(143, 84, 46));
        jLabel15.setText("Thêm sản phẩm thú cưng");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        btnImage.setText("Chọn ảnh");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });
        getContentPane().add(btnImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 90, -1));

        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 410, 220));

        lblImgPath.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        getContentPane().add(lblImgPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 410, 20));

        getContentPane().add(cbProductCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 190, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Giảm giá:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, 20));

        txtDiscount.setText("20");
        getContentPane().add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 230, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mã code:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 20));

        lblBarcode.setText("jLabel7");
        getContentPane().add(lblBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 190, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/@reallygreatsite/4.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtNameKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<Petcategory> list = PetCategoryDao.getAllRecords();
        Iterator<Petcategory> itr = list.iterator();
        while(itr.hasNext()){
            Petcategory categoryObj = itr.next();
            cbPetCategory.addItem(new CategoryItem(categoryObj.getId(), categoryObj.getName()));
        }
        ArrayList<Productcategory> list1 = ProductCategoryDao.getAllRecords();
        Iterator<Productcategory> itr1 = list1.iterator();
        while(itr1.hasNext()){
            Productcategory categoryObj = itr1.next();
            cbProductCategory.addItem(new CategoryItem(categoryObj.getId(), categoryObj.getName()));
        }
        int randomBarcode = (int)((Math.random() * 9000000)+1000000);
        lblBarcode.setText(Integer.toString(randomBarcode));
//        createPDF(Integer.toString(randomBarcode) + ".pdf", Integer.toString(randomBarcode));
    }//GEN-LAST:event_formComponentShown

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            // TODO add your handling code here:
            Product product = new Product();
            product.setPet_category_id((int)((CategoryItem)cbPetCategory.getSelectedItem()).getId());
            product.setProduct_category_id((int)((CategoryItem)cbProductCategory.getSelectedItem()).getId());
            product.setName(txtName.getText());
            product.setDescription(txtDescription.getText());
            product.setQuantity(Integer.parseInt(txtQuantity.getText()));
            product.setVendor_price(Integer.parseInt(txtVendorPrice.getText()));
            product.setRetail_price(Integer.parseInt(txtRetailPrice.getText()));
            product.setBarcode(lblBarcode.getText());
            product.setDiscount(Integer.parseInt(txtDiscount.getText()));
            createPDF(lblBarcode.getText() + ".pdf", lblBarcode.getText());
            product.setImage(lblImgPath.getText());
            
            int id = ProductDao.save(product);
            
            String imageProductPath = lblImgPath.getText();
            String newPath = System.getProperty("user.dir") + "\\src\\file\\productImage\\";
                    
            File directory = new File(newPath);
            if(!directory.exists()){
                directory.mkdir();
            }
            
            File sourceFile = null;
            File destinationFile = null;
            String extension = imageProductPath.substring(imageProductPath.lastIndexOf('.') + 1);
            sourceFile = new File(imageProductPath);
            destinationFile = new File(newPath + Integer.toString(id) + "." + extension);
            
            Files.copy(sourceFile.toPath(), destinationFile.toPath());
            
            ProductDao.updateImage(id, "\\src\\file\\productImage\\" + id + "." + extension);
            
            Date today = new Date();
            ProductDao.importQuantityOfProduct(id, product.getQuantity(), today);
            
            setVisible(false);
            new AddNewProduct().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AddNewProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbPetCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPetCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPetCategoryActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser f = new JFileChooser(new File("C:\\"));
            int result = f.showSaveDialog(null);
            if(result == JFileChooser.APPROVE_OPTION){
                File selectedFile = f.getSelectedFile();
                lblImage.setIcon(ResizeImage(String.valueOf(selectedFile)));
                lblImgPath.setText(selectedFile.getPath());
            }             
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }  
    }//GEN-LAST:event_btnImageActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<CategoryItem> cbPetCategory;
    private javax.swing.JComboBox<CategoryItem> cbProductCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBarcode;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImgPath;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtRetailPrice;
    private javax.swing.JTextField txtVendorPrice;
    // End of variables declaration//GEN-END:variables
}
