/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package petshop.management.system;

import dao.PetCategoryDao;
import dao.PetDao;
import dao.ProductDao;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Pet;
import model.Petcategory;
import model.Product;
import model.User;

/**
 *
 * @author Admin
 */
public class ManagePet extends javax.swing.JFrame {
    public User user;

    /**
     * Creates new form ViewEditDeleteProduct
     */
    public ManagePet() {
        initComponents();
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public ManagePet(User user) {
        this.user = user;
        initComponents();
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    class CategoryItem
    {
        private int id = 0;
        private String name = "";
        public CategoryItem(int id, String name) {
            this.id = id;
            this.name = name;
        } 
        public int getId(){
            return id;
        }
        public String getName(){
            return name;
        }
        
        @Override
        public String toString() {
            return name;
        }
    }
    
    public ImageIcon ResizeImage(String ImagePath){
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    public void validateFields(){
//        String name = txtName.getText();
//        String price = txtPrice.getText();
//        String category = (String)jComboBox1.getSelectedItem();
//        if(!name.equals("") && !price.equals("") && category != null){
//            btnUpdate.setEnabled(true);
//        } else {
//            btnUpdate.setEnabled(false);
//        }
    }
    
    public void searchTable(){
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        String id = txtIdSearch.getText();
        int category = (int)((CategoryItem)cbPetCateSearch.getSelectedItem()).getId();
        ArrayList<Pet> list = PetDao.searchPet(id, category);
        Iterator<Pet> itr = list.iterator();
        while(itr.hasNext()){           
            Pet petObj = itr.next();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dateBirthday = sdf.format(petObj.getBirthday());
            String dateImportday = sdf.format(petObj.getImportday());
            dtm.addRow(new Object[]{
                petObj.getId(), 
                petObj.getCategory_id(),
                petObj.getCategory_name(), 
                petObj.getType(),
                petObj.getColor(),
                dateBirthday,
                petObj.getSex(),
                petObj.getWeight(),
                petObj.getHeight(),
                petObj.getVendor_price(),
                petObj.getRetail_price(),
                petObj.getDescription(),
                dateImportday,
                petObj.getImage(),
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        cbCategory = new javax.swing.JComboBox<>();
        txtColor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dateBirthday = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        txtHeight = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtVendorPrice = new javax.swing.JTextField();
        txtRetailPrice = new javax.swing.JTextField();
        dateImportday = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblImgPath = new javax.swing.JLabel();
        txtIdSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbPetCateSearch = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 20, 40, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblId.setText("00");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 20, -1));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnClear.setText("Hủy");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 80, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã loài", "Loài", "Giống", "Màu lông", "Ngày sinh", "Giới tính", "Cân nặng", "Chiều cao", "Giá nhập", "Giá bán", "Mô tả", "Ngày nhập", "Đường dẫn"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 1200, 260));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Giống:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 47, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Loài:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });
        txtType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTypeKeyReleased(evt);
            }
        });
        getContentPane().add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 190, -1));

        cbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(cbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 190, -1));

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtColorKeyReleased(evt);
            }
        });
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 190, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Màu lông:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Ngày sinh:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 20));
        getContentPane().add(dateBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 190, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Giới tính:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, 20));

        rbMale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbMale.setText("Đực");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });
        getContentPane().add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        rbFemale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbFemale.setText("Cái");
        rbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemaleActionPerformed(evt);
            }
        });
        getContentPane().add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Cân nặng:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, 20));

        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        getContentPane().add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 40, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("kg");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Chiều cao:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Giá nhập:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, -1, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Giá bán:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Mô tả:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Ngày nhập:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, 20));

        jScrollPane2.setHorizontalScrollBar(null);

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane2.setViewportView(txtDescription);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 230, 60));
        getContentPane().add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 40, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("cm");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, 20));
        getContentPane().add(txtVendorPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 410, -1));
        getContentPane().add(txtRetailPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 410, -1));
        getContentPane().add(dateImportday, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 410, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(143, 84, 46));
        jLabel20.setText("Quản lý thú cưng");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        btnImage.setText("Chọn ảnh");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });
        getContentPane().add(btnImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 90, -1));

        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 360, 220));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Thêm thú cưng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 310, -1));

        lblImgPath.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        getContentPane().add(lblImgPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 360, 20));

        txtIdSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtIdSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Loài");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, 20));

        ArrayList<Petcategory> list = PetCategoryDao.getAllRecords();
        Iterator<Petcategory> itr = list.iterator();
        cbPetCateSearch.addItem(new CategoryItem(0, "Tất cả"));
        while(itr.hasNext()){
            Petcategory categoryObj = itr.next();
            cbPetCateSearch.addItem(new CategoryItem(categoryObj.getId(), categoryObj.getName()));
        }
        cbPetCateSearch.setSelectedItem("Tất cả");
        cbPetCateSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPetCateSearchActionPerformed(evt);
            }
        });
        getContentPane().add(cbPetCateSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 120, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/@reallygreatsite/4.png"))); // NOI18N
        jLabel6.setText(" ");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            // TODO add your handling code here:
            //        Product product = new Product();
            //        int id = Integer.parseInt(lblId.getText());
            //        product.setId(id);
            //        product.setName(txtName.getText());
            //        product.setCategory((String)jComboBox1.getSelectedItem());
            //        product.setPrice(txtPrice.getText());
            //        ProductDao.update(product);
            //
            Pet pet = new Pet();
            int id = Integer.parseInt(lblId.getText());
            pet.setId(id);
            pet.setCategory_id((int)((CategoryItem)cbCategory.getSelectedItem()).getId());
            System.out.println((int)((CategoryItem)cbCategory.getSelectedItem()).getId());
            pet.setType(txtType.getText());
            pet.setColor(txtColor.getText());
            pet.setBirthday(dateBirthday.getDate());
            if(rbFemale.isSelected()){
                pet.setSex(rbFemale.getText());
            }
            if(rbMale.isSelected()){
                pet.setSex(rbMale.getText());
            }
            pet.setWeight(Double.parseDouble(txtWeight.getText()));
            pet.setHeight(Double.parseDouble(txtHeight.getText()));
            pet.setRetail_price(Integer.parseInt(txtRetailPrice.getText()));
            pet.setVendor_price(Integer.parseInt(txtVendorPrice.getText()));
            pet.setDescription(txtDescription.getText());
            pet.setImportday(dateImportday.getDate());

            String imagePetPath = lblImgPath.getText();
            String newPath = System.getProperty("user.dir") + "\\src\\file\\petImage\\";

            File directory = new File(newPath);
            if(!directory.exists()){
                directory.mkdir();
            }

            File sourceFile = null;
            File destinationFile = null;
            String extension = imagePetPath.substring(imagePetPath.lastIndexOf('.') + 1);
            sourceFile = new File(imagePetPath);
            destinationFile = new File(newPath + Integer.toString(id) + "." + extension);

            Files.copy(sourceFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            pet.setImage("\\src\\file\\petImage\\" + id + "." + extension);

            PetDao.update(pet);
            setVisible(false);
            new ManagePet().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ManagePet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        jTable1.setAutoCreateRowSorter(true);
        ArrayList<Pet> list = PetDao.getAllRecords();
        Iterator<Pet> itr = list.iterator();
        while(itr.hasNext()){           
            Pet petObj = itr.next();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dateBirthday = sdf.format(petObj.getBirthday());
            String dateImportday = sdf.format(petObj.getImportday());
            dtm.addRow(new Object[]{
                petObj.getId(), 
                petObj.getCategory_id(),
                petObj.getCategory_name(), 
                petObj.getType(),
                petObj.getColor(),
                dateBirthday,
                petObj.getSex(),
                petObj.getWeight(),
                petObj.getHeight(),
                petObj.getVendor_price(),
                petObj.getRetail_price(),
                petObj.getDescription(),
                dateImportday,
                petObj.getImage(),
            });
            jTable1.getColumnModel().getColumn(1).setMinWidth(0);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(0);
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            // TODO add your handling code here
            int index = jTable1.getSelectedRow();
            if(jTable1.getRowSorter() != null){
                index = jTable1.getRowSorter().convertRowIndexToModel(index);
            }

            TableModel model = jTable1.getModel();
            String id = model.getValueAt(index, 0).toString();
            lblId.setText(id);
            String category = model.getValueAt(index, 2).toString();
            String type = model.getValueAt(index, 3).toString();
            txtType.setText(type);
            String color = model.getValueAt(index, 4).toString();
            txtColor.setText(color);
            Date birthDate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(index, 5).toString());
            dateBirthday.setDate(birthDate);
            String sex = model.getValueAt(index, 6).toString();
            rbMale.setSelected(false);
            rbFemale.setSelected(false);
            if(sex.equals("Đực")){
                rbMale.setSelected(true);
            }
            if(sex.equals("Cái")){
                rbFemale.setSelected(true);
            }
            String weight = model.getValueAt(index, 7).toString();
            txtWeight.setText(weight);
            String height = model.getValueAt(index, 8).toString();
            txtHeight.setText(height);
            String vendor_price = model.getValueAt(index, 9).toString();
            txtVendorPrice.setText(vendor_price);
            String retail_price = model.getValueAt(index, 10).toString();
            txtRetailPrice.setText(retail_price);
            String description = model.getValueAt(index, 11).toString();
            txtDescription.setText(description);
            Date importDate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(index, 12).toString());
            dateImportday.setDate(importDate);
            lblImage.setIcon(ResizeImage(String.valueOf(System.getProperty("user.dir") + model.getValueAt(index, 13).toString())));
            lblImgPath.setText(System.getProperty("user.dir") + model.getValueAt(index, 13).toString());
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            cbCategory.removeAllItems();
            cbCategory.addItem(new CategoryItem(Integer.parseInt(model.getValueAt(index, 1).toString()), category));
            ArrayList<Petcategory> categoryList = PetCategoryDao.getAllRecords();
            Iterator<Petcategory> categoryItr = categoryList.iterator();
            while(categoryItr.hasNext()){
                Petcategory categoryObj = categoryItr.next();
                if(!categoryObj.getName().equals(category)){
                    cbCategory.addItem(new CategoryItem(categoryObj.getId(), categoryObj.getName()));
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(ManagePet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String id = lblId.getText();
        int a = JOptionPane.showConfirmDialog(null, "Bạn có chắn muốn XÓA thú cưng này", "Select", JOptionPane.YES_NO_OPTION);
        if( a == 0 ){
            PetDao.delete(id);
            setVisible(false);
            new ManagePet().setVisible(true);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ManagePet().setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void txtTypeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTypeKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtTypeKeyReleased

    private void cbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoryActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtColorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtColorKeyReleased

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleActionPerformed

    private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemaleActionPerformed

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser f = new JFileChooser(new File("C:\\"));
                int result = f.showSaveDialog(null);
                if(result == JFileChooser.APPROVE_OPTION){
                    File selectedFile = f.getSelectedFile();
                    lblImage.setIcon(ResizeImage(String.valueOf(selectedFile)));
                    lblImgPath.setText(selectedFile.getPath());
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
    }//GEN-LAST:event_btnImageActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new AddNewPet().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtIdSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdSearchKeyReleased
        // TODO add your handling code here:
        searchTable();
    }//GEN-LAST:event_txtIdSearchKeyReleased

    private void cbPetCateSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPetCateSearchActionPerformed
        // TODO add your handling code here:
        searchTable();
    }//GEN-LAST:event_cbPetCateSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<CategoryItem> cbCategory;
    private javax.swing.JComboBox<CategoryItem> cbPetCateSearch;
    private com.toedter.calendar.JDateChooser dateBirthday;
    private com.toedter.calendar.JDateChooser dateImportday;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImgPath;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtIdSearch;
    private javax.swing.JTextField txtRetailPrice;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtVendorPrice;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
